### ISSUE TITLE
Deleting all text in input bugs out the autocomplete popover.

### ISSUE THREAD

**Issue by shaneajeffery** [anubra266/choc-autocomplete#128]
I'm not sure if someone has a fix for this or has the same issue, but I'm hoping someone can point me in the right direction.

If I go ahead and choose a selection from the dropdown popover, it gets properly placed into the input.  If, however, I delete the text in the input either by selecting all of the text or just doing one character at a time until there is nothing left, the popover shows up for a split second and then disappears.

https://user-images.githubusercontent.com/69131241/155605347-2cfd7822-2efc-47cf-8243-ab4ecb39cf72.mp4

Anyone else running into this issue?

**Comment by anubra266** [comment]
Hi @shaneajeffery I don't really understand the Issue

**Comment by Hades42Prox** [comment]
I also want to ask the same thing. When the input field is empty, we still want to have some suggestion or other pre-defined suggestion items. choc-autocomplete currently could not do that (or may be I have not known yet). If choc-autocomplete is able to, please give some examples in codesandbox since all your example just close all the suggestion items when <AutoCompleteInput> is empty

I already tried to put some props in API reference but nothing seem to work

**Comment by Hades42Prox** [comment]
All good, I figure out
@shaneajeffery
You could put the `suggestWhenEmpty` props into `AutoComplete` component

```jsx
<AutoComplete openOnFocus suggestWhenEmpty>
  // other component inside
   ... 
</AutoComplete>

```

**Comment by anubra266** [comment]
Thanks @Hades42Prox
