### ISSUE TITLE
Allow users to change the filter method

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#18]
Should change this line for allowing a user to provide a custom function that filters the list.
**Use case:** I want a fuzzy search, so the function will receive the Input value, all options and the option value; perform the operation and return true to validate the option.
https://github.com/anubra266/choc-autocomplete/blob/069d49d12639dc0bd425de689afb75fe35317b2d/src/helpers/input.ts#L25

**Comment by SpencerKaiser** [comment]
@anubra266 I actually just ran into this issue as well with my address typeahead.

In my situation, I actually _**never**_ want filtering because my backend is returning results that are already filtered. What do you think about adding a `disableFilter` prop so the user doesn't need to add `filter={() => true}`?
