### ISSUE TITLE
[Dev environment] Local repository install in a real project

### ISSUE THREAD

**Issue by Richi2293** [anubra266/choc-autocomplete#182]
Hi,

i'm trying to test the library in a real project, i'm trying with the "npm link" (or yarn link) command but it's not working properly.

For example I have a warning:
"You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used."

And the css style is not loading:
<img width="242" alt="image" src="https://github.com/anubra266/choc-autocomplete/assets/5848941/c9629321-111d-4d3b-8f7a-eba141ea8ad6">

It seems limiting to me to be able to test the example and that's it, it would also be useful to have a small documentation on how to test it on a real project.

While I'm working on the local repository getting it to work in a real project, I thought it would be handy to open an issue.
Thanks

**Comment by Kysluss** [comment]
Hi @Richi2293,

While testing another issue, I was also unable to get npm link to work, but it's probably a limitation of my understanding.  Below is how I was able to do it for my issue:

1. Clone repo locally
2. Run npm pack - this will create a tgz file
3. In your other project, run npm install path/to/above-file.tgz

**Comment by Kysluss** [comment]
@Richi2293 

While working on an issue today, I was able to find something that worked a little smoother.  It's a couple extra steps, but the benefit is you no longer have to delete the node_modules folder and reinstall everything.

1. Clone repo locally (create branch, npm install, etc)
2. Run npm version X.X.X-alpha.1 where X.X.X is the next version
3. Make code changes and commit
4. Run npm version prerelease (this will increase version to -alpha.2, -alpha.3, etc)
5. Run npm run build and npm pack to create tgz file
6. In other project, run npm install path/to/above-file.tgz
7. Repeat steps 3 - 6 as needed

This is a few extra steps, but each time you install the tgz file, it will correctly overwrite the prior one.  This is because npm version prerelease creates a correct symver version increase, so it knows it's a new version.  Hope this helps you in future projects as it has me!

**Comment by Kysluss** [comment]
I'm hoping between the steps outline above and the recent commits in #216 to help run it locally, this should be all set.  Let me know if there's anything else that should be updated.
