### ISSUE TITLE
Fix Emphasis prop

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#33]
Highlighting with emphasis prop, does not work well with text transformation.

**Comment by j4chou** [comment]
Hi Abraham, thank you so much for all your work on this library.
I'm encountering the same issue using the emphasize prop on transformed text (e.g. searching for "Ja" in "Japan" will cause the suggestions to display "JaPan" instead of "Japan"); this can be reproduced using the codesandbox link in the readme which is using v5.1.5 (although I'm on v4.22.0).
What would be the fix for this issue?
Thanks in advance.
