### ISSUE TITLE
Using Autocomplete with react-instantsearch-dom HOCs

### ISSUE THREAD

**Issue by SteveWallace** [anubra266/choc-autocomplete#66]
I'm currently trying to implement a search field using react-instantsearch-dom and chakra-autocomplete. I seem to be hitting a wall when rendering the AutoCompleteList. I believe the issue is that the reference or context of AutoComplete is getting lost but I'm not sure how to solve it. 

The search box part looks like this 
``` javascript
  <AutoComplete rollNavigation id="autoTop" itemRef="auto">
    <AutoCompleteInput
        value={currentRefinement}
        variant="filled"
        placeholder="Search..."
        minW="500px"
        autoFocus
        onChange={(e) => handleQuery(e)}
        id="auto-input"
      />
      <SearchResults />
    </AutoComplete>
````

With the SearchResults component looking like this and then being wrapped in the instantsearch HOC with connectHits()

```javascript
const HitBase = ({ hits, handleClick }: HitProps) => {
  console.log(hits)

  return (
    <AutoCompleteList >
      {hits.map((hit) => (
        <AutoCompleteItem key={hit.title} value={hit.title}>
          <Poster id={hit.id} slug={hit.poster_path} title={hit.title} />
          <Text>{hit.title}</Text>
        </AutoCompleteItem>
      ))}
    </AutoCompleteList>
  )
}
const SearchResults = connectHits(HitBase)
```

Is there a way to maintain the reference between the two components? My assumption is that the hits HOC is what actually breaks it but I am not sure how to get around it.

**Comment by anubra266** [comment]
Ive not tested this, but try importing 'forwardRef' from chakra UI and pass the provided ref to 'AutocompleteList' component.

**Comment by SteveWallace** [comment]
Alright, I will give it a try and report back.

**Comment by SteveWallace** [comment]
I'm not able to get it to work, though I could be using forwardRef incorrectly. I tried two different versions. One where I built the full AutoComplete component like this.

```javascript
const SearchAutoComplete = forwardRef<AutoCompleteProps, "AutoComplete">((props, ref) => (
  <AutoComplete id="autoTop"  ref={ref}>
    <AutoCompleteInput
      value={props.currentRef}
      variant="filled"
      placeholder="Search..."
      minW="500px"
      autoFocus
      id="auto-input"
      ref={ref}
    />
    <SearchResults ref={ref} />
  </AutoComplete>
))
```
With SearchResults 

```javascript
const HitBase = ({ hits, handleClick, ref}: HitProps) => {
  console.log(hits)

  return (
    <AutoCompleteList ref={ref}>
      {hits.map((hit) => (
        <AutoCompleteItem key={hit.title} value={hit.title} ref={ref}> 
          <Poster id={hit.id} slug={hit.poster_path} title={hit.title} />
          <Text>{hit.title}</Text>
        </AutoCompleteItem>
      ))}
    </AutoCompleteList>
  )
}
const SearchResults = connectHits(HitBase)
```

And a second where I just built the AutoCompleteList
```javascript
const SearchAutoCompleteList = forwardRef<AutoCompleteListProps, "AutoCompleteList">(
  (props, ref) => (
    <AutoCompleteList ref={ref}>
      <SearchResults ref={ref} />
    </AutoCompleteList>
  )
)
```
Calling it inside a normal AutoComplete and the SearchResults only being 
```javascript
const HitBase = ({ hits, ref, handleClick }: HitProps) => {
  console.log(hits)

  return (
    <>
      {hits.map((hit, id) => (
        <AutoCompleteItem key={`${id}${hit.title}`} value={hit.title} ref={ref}>
          <Poster id={hit.id} slug={hit.poster_path} title={hit.title}  />
          <Text>{hit.title}</Text>
        </AutoCompleteItem>
      ))}
    </>
  )
}
````

Neither made any difference. In both instances the empty state object gets added and I just get the 'no options found!' dialog. 

Oh, also as I was looking through the .dev files of the component I did notice that their is a misspelling in the AutoComplete context error, autocomplete is misspelled as autoomplete.

**Comment by anubra266** [comment]
Hi @SteveWallace I'm afraid I haven't found a workaround for this yet, because, the approach is of the package is to scan children for `AutoCompleteItem`s but separating it into a different component, makes it impossible to access those Items.

The only way to overcome this as at now(not implemented yet); the user will have to pass the options as an array prop to the `AutoComplete` component, so that can be used instead of scanning for the `AutoCompleteItem` components.

I took the present approach because of [this poll](https://discord.com/channels/660863154703695893/660863154703695896/842545316498112512).

Though it'll be great if anyone could come up with a better way of scanning the components. Right now I use `child.type.displayName`, while looping the React.children.
<img width="867" alt="CleanShot 2021-09-13 at 00 25 27@2x" src="https://user-images.githubusercontent.com/30869823/133006031-104879a9-96a8-4640-90b3-736404f10910.png">

**Comment by SteveWallace** [comment]
@anubra266 No problem! I get why you built it that way and it makes sense. I suspected that would end up the case. I appreciate you having a look.

**Comment by anubra266** [comment]
Hi @SteveWallace found a way around this, so it's fixed in [v4.6.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.6.0).

**Comment by SteveWallace** [comment]
Nice, I'll give it a go tonight.

**Comment by anubra266** [comment]
@SteveWallace I'm really sorry, I'll be reversing this till I find a better way. The current approach is now blocking a lot of things.

**Comment by Kysluss** [comment]
Hello @SteveWallace .  I'm wondering if you're still having an issue with this.  I am not all that familiar with react-instantsearch, but if you can post a quick example of the issue, I may be able to help.  There have been a lot of releases since this issue was opened, so I'm wondering if you're still seeing it.
